MODULE_COMMANDS = {
    "basic": [".basic root-check", ".basic profile", ".basic sect-list"],
    "cultivation": [".fanren on normal", ".fanren on deep", ".fanren status"],
    "sect": [".sect panel", ".sect sign", ".sect teach", ".sect bounty"],
    "breakthrough": [
        ".breakthrough jiedan",
        ".breakthrough yuanying",
        ".breakthrough huashen",
    ],
    "battle": [".battle pvp @目标", ".battle rank", ".battle test", ".battle tower"],
    "artifact": [".artifact status", ".artifact repair 法宝", ".artifact spirit"],
    "inventory": [
        ".inventory bag",
        ".inventory learn 物品",
        ".inventory craft 物品*数量",
    ],
    "other": [
        ".卜筮问天",
        ".闯塔",
        ".六道轮回盘",
        ".赌石",
        ".押 大 100",
        ".对赌 500",
    ],
    "estate": [
        ".洞府",
        ".升级灵脉",
        ".升级静室",
        ".布置景观 景观名",
        ".上架至万宝阁 物品名",
    ],
    "companion": [
        ".companion search",
        ".companion dream",
        ".companion place",
        ".companion recall",
    ],
    "market": [".market board", ".market auction", ".market bounty", ".market gamble"],
    "stock": [
        ".股市",
        ".大盘",
        ".领股息",
        ".个股 IDX_CODE",
        ".买入 IDX_CODE 金额",
        ".卖出 IDX_CODE 数量",
        ".我的持仓",
        ".融资买入 IDX_CODE 金额",
        ".融资平仓 IDX_CODE 数量",
        ".股市任务",
    ],
    "dungeon": [
        ".开启虚天殿",
        ".加入副本 123",
        ".进入虚天殿",
        ".开启昆吾山",
        ".开启坠魔谷",
    ],
    "diplomacy": [".diplomacy map", ".diplomacy favor 宗门", ".diplomacy ally 宗门"],
    "shop": [".shop open"],
}
